all:
	g++  src/main.cpp src/UI/UI.cpp src/SparseMatrix.cpp src/UsualMatrix.cpp -o LR14
gdb:
	g++ -g src/main.cpp src/UI/UI.cpp src/SparseMatrix.cpp src/UsualMatrix.cpp -o LR14
profile:
	g++ -pg src/main.cpp src/UI/UI.cpp src/SparseMatrix.cpp src/UsualMatrix.cpp -o LR14
